name: Deploy Web2 to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Rsync files to server
        uses: burnett01/rsync-deployments@v4
        with:
          switches: -avz --delete
          path: .
          remote_path: /var/www/web2.com/public_html
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Fix permissions & reload nginx
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo chown -R ubuntu:www-data /var/www/web1.com/public_html || true
            sudo chmod -R 755 /var/www/web2.com/public_html || true
            sudo systemctl reload nginx || true
